apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: igya7knbi-nodejs 
  janus-idp.io/tekton: igya7knbi-nodejs
  backstage.io/kubernetes-id: igya7knbi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: igya7knbi-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml